name: Windows-CRD

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      env:
        NEW_PASS: ${{ secrets.NEW_PASS }}
      run: ./setup.ps1
    - name: Initialize ngrok
      env:
        NGROKAUTHTOKEN: ${{ secrets.NGROKAUTHTOKEN }}
      run: ./setup-ngrok.ps1
